name: Austin Hansen
description: "Blogging about Ruby, Rails, and web development"
meta_description: "Austin Hansen, blogging about Ruby, Rails, and web development"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
